import os
import math
import sys
import time

#class storing the data structures needed for each limit order placed
#time began, cancellation time (generated by a poisson process), number of shares
class LimitOrder:
    def __init__(self, id, time_began, cancellation_time, order_size):
        self.id = id #an id from the pool of remaining limit orders - a number
        self.time_began = time_began #of type float - system time called using time.time()
        self.cancellation_time = cancellation_time #of type float
        self.order_size = order_size #units of numbers
        self.end_time = time_began + cancellation_time
        #print("A Limit Order created.")

    def show_characteristics(self): #just for debugging purposes
        print("Limit Order id = %d, Order Size = %d, Time Began = %f, Cancellation Time = %f, End Time = %f"
              % (self.id, self.order_size, self.time_began, self.cancellation_time, self.end_time))

    def __del__(self):
        print("Deleted Limit Order %d" % self.id)


if __name__ == "__main__":
    begin_time = time.time()
    lo1 = LimitOrder(1, time.time() - begin_time, 4.56, 3)
    lo1.show_characteristics()
    del lo1
    #lo1.show_characteristics()



